site_name: 'Relax-and-Recover (ReaR) User Guide Documentation'
site_description: 'Reference documentation for Relax-and-Recover (ReaR)'
theme:
  name: 'readthedocs'
  custom_dir: rear_theme/
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
docs_dir: docs/
site_dir: site/
repo_name: 'rear/rear-user-guide'
repo_url: 'https://github.com/rear/rear-user-guide'
copyright: 'Copyright 2025 - CC0 1.0 Universal'
extra_css:
  - css/rear.css
google_analytics:
  - '366986045'
  - 'auto'
use_directory_urls: false
edit_uri: ''
markdown_extensions:
  - admonition:
  - toc:
      permalink: True
      separator: "_"
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
plugins:
  - search:
      min_search_length: 2
  - redirects:
nav:
  - index.md
  - WELCOME:
    - 'Get started!': 'welcome/index.md'
  - BASICS:
    - 'Introduction': 'basics/introduction.md'
    - 'Bit of History': 'basics/history.md'
    - 'Getting started with ReaR': 'basics/getting-started.md'
    - 'Basic configuration': 'basics/configuration.md'
    - 'Example of BACKUP=NETFS': 'basics/backup_netfs.md'
  - SCENARIOS:
    - 'Scenarios Overview': 'scenarios/index.md'
    - 'Internal Backup with tar to NFS server': 'scenarios/netfs_nas.md'
    - 'Internal Backup with rsync to NFS server': 'scenarios/netfs_rsync.md;
    - 'External Backup using RBME': 'scenarios/rbme.md'
    - 'External Backup using restic': 'scenarios/restic.md'
  - DEVELOPMENT:
    - 'Make a pull request with GitHub': 'development/github-pr.md'
    - 'How to squash git log comments into one line': 'development/squash-git-log-commments.md'
  - RELEASE NOTES:
    - 'Release Notes': 'releasenotes/index.md'
    - 'Release Notes ReaR 2.9': 'releasenotes/rear29.md'
    - 'Release Notes ReaR 2.8': 'releasenotes/rear28.md'
    - 'Release Notes ReaR 2.7': 'releasenotes/rear27.md'
    - 'Release Notes ReaR 2.6': 'releasenotes/rear26.md'
    - 'Known Problems and Workarounds': 'releasenotes/knownproblems.md'
  - ISSUES:
    - 'Issues History': 'issues/index.md'
  - LEGAL:
    - 'Contributing': 'legal/contributing/index.md'
    - 'License': 'legal/license/index.md'
